### PR TITLE
Add bash aliases

### PR DESCRIPTION
**Pull request by frahugo**

### CODE REVIEW

**Comment by frahugo** [comment]
@nicholasjhenry please review

**Comment by nicholasjhenry** [comment]
@frahugo I've introduced a `bashrc` file in #2 This means we won't need to add this file manually. It will load up your local `bashrc.local` file afterwards. Thoughts?

**Comment by nicholasjhenry** [comment]
Related, the `aliases` file is in the root, this makes up "compatible" with the thoughtbot dotfiles (not sure if that is necessarily a concern).

**Comment by nicholasjhenry** [comment]
@frahugo I find aliases like these are personal preferences and we should just include them in our own personal overrides. We now have a `.zshrc.local` we're we can add these in. Are you good with that?

**Comment by nicholasjhenry** [comment]
Closing due to being stale.

**Pull request closed without merging**
